### ISSUE TITLE
Pathfinders cannot handle edges of canvas

### ISSUE THREAD

**Issue by embeddedt** [freegroup/draw2d#52]
Whenever a connection that uses one of the pathfinding routers (Maze or Sketch) touches the edge of the canvas, the pathfinding logic is unable to handle the situation, resulting in a long stream of exceptions that eventually leads to bad state in the rest of the library.

The workaround I am using in my project right now is to apply a `RegionEditPolicy` to all of my draggable elements that prevents them from reaching the very edge. However, this should not be needed.

To reproduce, visit https://freegroup.github.io/draw2d/connection_router/index.html, select the Maze/Sketch connection router, and drag the square with two ports on the top along the top of the canvas. In the developer console, a lot of exceptions will be printed out and eventually the library seems to get into a bad state.

**Comment by embeddedt** [comment]
I also had to disable the ability to modify created connections by dragging (`conn.setDraggable(false);`) because otherwise they could be dragged to the edge of the canvas as well (reproducible with the same link).

**Comment by freegroup** [comment]
new link for the demo https://freegroup.github.io/draw2d/#/examples/connection_router

**Comment by freegroup** [comment]
should be fixed

**Comment by embeddedt** [comment]
I've tried it and the issue is still there. If you choose the Maze or Sketch modes, and then drag the square with a top port along the top edge of the screen, it will still print out some TypeErrors and the path does not update.
